#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
source "$SCRIPT_DIR/logs"
source "$SCRIPT_DIR/utils"

export XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"
log_setup "Creating symlinks for configurations."
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME/nvim"
ln -sf "$PWD/starship.toml" "$XDG_CONFIG_HOME/starship.toml"
ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
log_setup "Setup completed"