#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
source "$SCRIPT_DIR/logs"
source "$SCRIPT_DIR/utils"

export XDG_CONFIG_HOME="$HOME/.config"

common_directories=(
    $XDG_CONFIG_HOME
)

common_items=(
  "ghostty:$XDG_CONFIG_HOME/ghostty"
  "nix:$XDG_CONFIG_HOME/nix"
  "tmux/.tmux.conf:$HOME/.tmux.conf"
  "tmux/.tmux:$HOME/.tmux"
  "nvim:$XDG_CONFIG_HOME/nvim"
  "starship.toml:$XDG_CONFIG_HOME/starship.toml"
  "shell/zsh:$XDG_CONFIG_HOME/zsh"
  "shell/zsh/.zprofile:$HOME/.zprofile"
  "shell/zsh/.zshrc:$HOME/.zshrc"
  "shell/bash/.bashrc:$HOME/.bashrc"
)

create_directories "${common_directories[@]}"
create_symlinks "${common_items[@]}"

log_setup "Setup completed"
